/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsa.ca1;

import javax.swing.*;

/**
 *
 * @author Olivier Nowak
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    String input;
    listInterface mySLL = new laptopList();
    public GUI(laptopList list) { //recieve list when coming back
        initComponents();
        setLocationRelativeTo(null); //centres window
        this.mySLL = list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        rentBtn = new javax.swing.JButton();
        TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        queueBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setText("Add Laptop");
        addBtn.addActionListener(this::addBtnActionPerformed);
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, 30));

        rentBtn.setText("Rent Laptop");
        rentBtn.addActionListener(this::rentBtnActionPerformed);
        getContentPane().add(rentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, 30));

        TextField.addActionListener(this::TextFieldActionPerformed);
        getContentPane().add(TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 340, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel1.setText("Laptop Rental");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 310, 80));

        returnBtn.setText("Return Laptop");
        returnBtn.addActionListener(this::returnBtnActionPerformed);
        getContentPane().add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 30));

        listBtn.setText("View Laptops");
        listBtn.addActionListener(this::listBtnActionPerformed);
        getContentPane().add(listBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 110, 30));

        historyBtn.setText("View History");
        historyBtn.addActionListener(this::historyBtnActionPerformed);
        getContentPane().add(historyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 30));

        queueBtn.setText("Check Queue");
        getContentPane().add(queueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        input = TextField.getText();
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter a laptop ID");
        }else{
            mySLL.add(input);
            System.out.print(input+"added to list");
        }     
    }//GEN-LAST:event_addBtnActionPerformed

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed
        // TODO add your handling code here:
        input = TextField.getText();
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter a laptop ID");
        }else{
            laptop node = mySLL.findLaptop(input);
            if (node == null) {
                JOptionPane.showMessageDialog(this, "Laptop not found.");
            } else if (!node.getAvailable()) {
                JOptionPane.showMessageDialog(this, input + " is already rented.");
            } else {
                node.setAvailable(false);
                JOptionPane.showMessageDialog(this, input + " rented successfully.");
            }
        }  
    }//GEN-LAST:event_rentBtnActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        input = TextField.getText();
        if(input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter a laptop ID");
        }else{
            laptop node = mySLL.findLaptop(input);
            if (node == null) {
                JOptionPane.showMessageDialog(this, "Laptop not found.");
            } else if (node.getAvailable()) {
                JOptionPane.showMessageDialog(this, input + " is not currently rented out.");
            } else {
                node.setAvailable(true);
                JOptionPane.showMessageDialog(this, input + " returned successfully.");
            }
        }  
    }//GEN-LAST:event_returnBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
        listGUI myGUI = new listGUI((laptopList)mySLL); //switch window to listgui and pass list
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
        historyGUI myGUI = new historyGUI((laptopList)mySLL); //switch window to listgui and pass list
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> { laptopList list = new laptopList(); new GUI(list).setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listBtn;
    private javax.swing.JButton queueBtn;
    private javax.swing.JButton rentBtn;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
